---
title: "課堂練習模版"
author: "Krystal_410882049"
date: "2020-10-14"
output: output_format
params:
  id: "410882049"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
utils::browseURL("https://classroom.google.com/c/MTQxMzcyNjA2MDc0")
utils::browseURL("https://tpemartin.github.io/NTPU-R-for-Data-Science/")
```
```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```
```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
class(num)
class(int)
class(char)
class(logi)
```
```{r}
1.5+2.0
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
``


`
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```
```{r}
class("1.5")
class("2.0")

```
```{r}
a<-"1.5"
as.numeric(a)->a
a+4
```
```{r}
a<- factor(c("一","四","二"))
a
```

